api_key: "HVRei5S3ByqrSFn6Jwf65kz2W1VoWinPIhY6MPrL7wiC1EgT2nU7tzYYnpDNDRwP"
api_secret: "jreM5IJZeXbDew7rqEOXoR4y8EYdySfyJhx70lMW4IvxGOWiwSK8iEpR8w81fZz9"

telegram_token: "2120261546:AAELaLSG0kybwK0XKGVKPXnWA597Y6dplok"

user: "1881343603"